class nest::base::ruby {
  # Workaround ruby-lsp issue calling bundle with version argument
  # See: https://github.com/Shopify/ruby-lsp/issues/3022
  exec { '/bin/mv /usr/bin/bundle /usr/bin/bundle.real':
    onlyif => '/bin/grep -E "Generated by ruby-fakegem.eclass" /usr/bin/bundle',
  }
  ->
  file { '/usr/bin/bundle':
    mode    => '0755',
    owner   => 'root',
    group   => 'root',
    content => @(WRAPPER),
      #!/usr/bin/env ruby
      args = ARGV
      args.shift if args[0] =~ /^_.*_/
      exec('/usr/bin/bundle.real', *args)
      | WRAPPER
  }
}
