class nest::base::ruby {
  if $nest::puppet_forge_key {
    $bundler_puppetcore_credentials = "forge-key:${$nest::puppet_forge_key.unwrap}"
    $gemrc_content = Sensitive(epp('nest/ruby/gemrc.epp', {
      'puppet_forge_key' => $nest::puppet_forge_key.unwrap,
    }))
    $bundler_puppetcore_env_content = Sensitive(epp('nest/ruby/bundler-puppetcore-env.epp', {
      'bundler_puppetcore_credentials' => $bundler_puppetcore_credentials,
    }))
  } else {
    $gemrc_content = undef
    $bundler_puppetcore_env_content = undef
  }

  case $facts['os']['family'] {
    'Gentoo': {
      File {
        owner => 'root',
        group => 'root',
      }

      # Workaround ruby-lsp issue calling bundle with version argument
      # See: https://github.com/Shopify/ruby-lsp/issues/3022
      exec { '/bin/mv /usr/bin/bundle /usr/bin/bundle.real':
        onlyif => '/bin/grep -F "Generated by ruby-fakegem.eclass" /usr/bin/bundle',
      }
      ->
      file { '/usr/bin/bundle':
        mode    => '0755',
        content => @(WRAPPER),
          #!/usr/bin/env ruby
          args = ARGV
          args.shift if args[0] =~ /^_.*_$/
          exec('/usr/bin/bundle.real', *args)
          | WRAPPER
      }

      $gemrc_path = '/etc/gemrc'
      $gemrc_require = []

      $bundler_puppetcore_env_path = '/etc/profile.d/puppetcore-bundler.sh'
    }

    'Darwin': {
      File {
        owner => 'root',
        group => 'wheel',
      }

      package { 'ruby@3.4':
        ensure => installed,
      }

      file { '/opt/homebrew/opt/ruby@3.4/etc':
        ensure  => directory,
        mode    => '0755',
        require => Package['ruby@3.4'],
      }

      $gemrc_path = '/opt/homebrew/opt/ruby@3.4/etc/gemrc'
      $gemrc_require = [Package['ruby@3.4']]

      file { '/etc/profile.d':
        ensure => directory,
        mode   => '0755',
      }

      file_line { 'macos-profile-source-profile-d-puppetcore-bundler':
        path  => '/etc/profile',
        line  => '[ -r /etc/profile.d/puppetcore-bundler.sh ] && . /etc/profile.d/puppetcore-bundler.sh',
        match => 'puppetcore-bundler\.sh',
      }

      file_line { 'macos-zprofile-source-profile-d-puppetcore-bundler':
        path  => '/etc/zprofile',
        line  => '[ -r /etc/profile.d/puppetcore-bundler.sh ] && . /etc/profile.d/puppetcore-bundler.sh',
        match => 'puppetcore-bundler\.sh',
      }

      $bundler_puppetcore_env_path = '/etc/profile.d/puppetcore-bundler.sh'
    }

    'windows': {
      File {
        owner => 'Administrators',
        group => 'None',
      }

      package { ['ruby', 'rubygems']:
        ensure   => installed,
        provider => 'cygwin',
      }

      $gemrc_path = 'C:/tools/cygwin/etc/gemrc'
      $gemrc_require = [
        Package['ruby'],
        Package['rubygems'],
      ]

      $bundler_puppetcore_env_path = 'C:/tools/cygwin/etc/profile.d/puppetcore-bundler.sh'
    }
  }

  if $gemrc_content {
    file { $gemrc_path:
      ensure    => file,
      mode      => '0644',
      show_diff => false,
      content   => $gemrc_content,
      require   => $gemrc_require,
    }
  }

  if $bundler_puppetcore_env_content {
    file { $bundler_puppetcore_env_path:
      ensure    => file,
      mode      => '0644',
      show_diff => false,
      content   => $bundler_puppetcore_env_content,
    }
  } else {
    file { $bundler_puppetcore_env_path:
      ensure  => absent,
    }
  }
}
