apiVersion: v1
kind: Pod
metadata:
  name: kube-apiserver
spec:
  containers:
    - name: kube-apiserver
      readinessProbe:
        httpGet:
          path: /readyz?exclude=etcd-readiness
        periodSeconds: 15
