#!/bin/sh

set -eu

vpn_service='openvpn-client@nest.service'
bird_service='bird.service'
trusted_connection='Nest'

if ! command -v nmcli >/dev/null 2>&1; then
  exit 0
fi

if nmcli --terse --fields NAME connection show --active | grep -Fxq "${trusted_connection}"; then
  /bin/systemctl --no-block start "${bird_service}"
else
  /bin/systemctl --no-block start "${vpn_service}"
fi
