#!/bin/sh

set -eu

backup_root=$1
shift
[ "${1:-}" = '--' ]
shift
[ "$#" -gt 0 ]

generation_id="$(date -u +%Y%m%dT%H%M%S)-$$"
staging_root="${backup_root}/.staging"
staging="${staging_root}/${generation_id}"
generations="${backup_root}/generations"
generation="${generations}/${generation_id}"
current_tmp="${backup_root}/.current-${generation_id}"

install -d -m 0700 "$staging_root" "$generations"
install -d -m 0700 "$staging"
install -d -m 0700 "$staging/data"
cleanup() {
  rm -rf "$staging" "$current_tmp"
}
trap cleanup EXIT HUP INT TERM

"$@" "$staging/data/"
printf '%s\n' "$generation_id" > "$staging/.complete"
mv "$staging" "$generation"
ln -s "generations/${generation_id}" "$current_tmp"
mv -Tf "$current_tmp" "$backup_root/current"

trap - EXIT HUP INT TERM
